name = input("Enter your name: ")
roll = input("Enter your roll Number:")
reg = input("Enter your reg: ")
name2 = input("Enter Your Name: ")
roll2 = input("Enter your roll Number: ")
reg2 = input("Enter your reg: ")

print("Student Information")
print("-------------------")
print("Name: "+name)
print("Roll No: "+roll)
print("Reg No: "+reg)

print("\n\nStudent Information 2")
print("-------------------")
print("Name: "+name2)
print("Roll No: "+roll2)
print("Reg No: "+reg2)